[package]
name = "actix-broker"
version = "0.1.0"
authors = ["chris ricketts <chris.ricketts@steribar.com>"]

[dependencies]
actix = "0.7.4"
fnv = "1.0.6"
log = "0.4.5"

[dev-dependencies]
simple_logger = "0.5.0"
